### ISSUE TITLE
添加书籍问题

### ISSUE THREAD

**Issue by flyingtango** [ManfredHu/Books-Management-System#3]
在本地配置好后，在页面中添加书籍后并不能在管理全部书籍中看到我刚刚添加的书籍。在数据库表中添加后也未能在管理全部书籍中显示。求解~

**Comment by ManfredHu** [comment]
你可以试着看一下node输出报什么错误，每次进入肯定是去读取的数据库的内容的。
看下是否有缓存

**Comment by flyingtango** [comment]
是这样的，在admin.js中 添加书籍imageName和buyDate缺省，可是表t_book中buyDate不能为null，所以就添加不了。给buyDate定个值就行。

**Comment by flyingtango** [comment]
抱歉 不是 admin.js中 而是 adminctrl.js中 去掉//
