### ISSUE TITLE
登录不成功的问题

### ISSUE THREAD

**Issue by wxiaohui** [ManfredHu/Books-Management-System#6]
你好,我试了试用数据库中的账号密码,登录不成功,报了一个这样的错误 
F:\try\whiteboard\branches\Wang Xiaohui\Books-Management-System-master\app\node_modules\.2.14.1@mysql\lib\protocol\Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^
TypeError: fail is not a function
    at F:\try\whiteboard\branches\Wang Xiaohui\Books-Management-System-master\app\db\connection.js:19:13
你有遇到过吗?还是我下载的mysql模块版本不对?我是直接使用的npm install安装的所有的模块

**Comment by Aurasy** [comment]
你好，最后解决了吗，我也遇到了这样的问题
